<template>
	<view class="container h100">
		<view class="d-flex h100">
			<view class="nav-left" >
				<scroll-view id="leftScroll" scroll-y="true" class="h100" :scroll-top="leftScrollTop">
					<view v-for="(item,index) in classList" @click="changeType(index)" :class="{'active':currentIndex == index}" class="left-scroll-item item border-right border-bottom border-light-secondary py-1 font-md text-muted" :key="item.name">{{item.name}}</view>
				</scroll-view>
			</view>
			<view class="nav-right">
				<scroll-view scroll-y="true"  class="h100" :scroll-top="rightScrollTop" :scroll-with-animation="true" @scroll="scroll">
					<view class="row right-scroll-item"
					v-for="(item,index) in list" 
					:key="index">
						<text class="font-md span24-24 px-2">{{item.title}}</text>
						<view class="span24-8 text-center py-2"
						v-for="(item2,index2) in item.list" :key="index2"
						 @click="openDetail(item2)">
							<image :src="item2.cover"
							style="width: 120upx;height: 120upx;"></image>
							<text class="d-block">{{item2.name}}</text>
						</view>
					</view>
				</scroll-view>
			</view>
		</view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				leftScrollTop:0,
				rightScrollTop:0,
				itemHeight:0,
				rightDomsTop:[],
				leftDomsTop:[],
				list:[
					{
						title:'分类1',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
							
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类1'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类1'
							},
						]
					},
					{
						title:'分类2',
						list:[
							{
								cover:'/static/images/demo/cate_04.png',
								name:'分类2'
							},
							{
								cover:'/static/images/demo/cate_05.png',
								name:'分类2'
							},
							{
								cover:'/static/images/demo/cate_06.png',
								name:'分类2'
							},
							{
								cover:'/static/images/demo/cate_04.png',
								name:'分类2'
							},
							{
								cover:'/static/images/demo/cate_05.png',
								name:'分类2'
							},
							{
								cover:'/static/images/demo/cate_06.png',
								name:'分类2'
							}
						]
					},
					{
						title:'分类3',
						list:[
							{
								cover:'/static/images/demo/cate_07.png',
								name:'分类3'
							},
							{
								cover:'/static/images/demo/cate_08.png',
								name:'分类3'
							},
							{
								cover:'/static/images/demo/cate_09.png',
								name:'分类3'
							},{
								cover:'/static/images/demo/cate_07.png',
								name:'分类3'
							},
							{
								cover:'/static/images/demo/cate_08.png',
								name:'分类3'
							},
							{
								cover:'/static/images/demo/cate_09.png',
								name:'分类3'
							}
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类4',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类4'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类4'
							},
						]
					},
					{
						title:'分类5',
						list:[
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_01.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_02.png',
								name:'分类5'
							},
							{
								cover:'/static/images/demo/cate_03.png',
								name:'分类5'
							}
						]
					}
				],
				currentIndex:0,
				classList:[
					{name:'分类1'},
					{name:'分类2'},
					{name:'分类3'},
					{name:'分类4'},
					{name:'分类5'},
					{name:'分类6'},
					{name:'分类7'},
					{name:'分类8'},
					{name:'分类9'},
					{name:'分类10'},
					{name:'分类11'},
					{name:'分类12'},
					{name:'分类13'},
					{name:'分类14'},
					{name:'分类15'},
					{name:'分类16'},
					{name:'分类17'},
					{name:'分类18'},
					{name:'分类19'},
					{name:'分类20'},
					{name:'分类21'},
					{name:'分类22'}
				],
			}
		},
		watch:{
			currentIndex(val){
				uni.createSelectorQuery().in(this).select('#leftScroll').fields({
					size:true,
					scrollOffset:true
				},data=>{
					if(this.itemHeight*(val+1) > data.height+data.scrollTop || data.scrollTop > this.leftDomsTop[val]){
						this.leftScrollTop=this.leftDomsTop[val];
					}
				}).exec();
			}
		},
		onNavigationBarSearchInputClicked(){
			uni.navigateTo({
				url:'../search/search'
			})
		},
		onReady() {
			const query = uni.createSelectorQuery().in(this);
			query.selectAll('.left-scroll-item').fields({size:true,scrollOffset:true,rect:true},data => {
			  this.leftDomsTop = data.map(v=> v.top);
			  this.itemHeight=data[0].height;
			  console.log(this.itemHeight,'itemHeight',data)
			}).exec();
			query.selectAll('.right-scroll-item').boundingClientRect(data => {
			   this.rightDomsTop = data.map(v=> v.top)
			}).exec();
		},
		methods: {
			changeType(index){
				this.currentIndex=index;
				this.rightScrollTop=this.rightDomsTop[index];
			},
			scroll(e){
				let scrollTop=e.detail.scrollTop;
				this.rightDomsTop.forEach((item,index)=>{
					if(item <= scrollTop){
						this.currentIndex=index;
						return false;
					}
				});
			},
			openDetail(){
				uni.navigateTo({
					url:'../search-list/search-list'
				});
			}
		}
	}
</script>

<style scoped>
.nav-left{
	width:22%;
	height:100%;
}
.nav-right{
	width:78%;
	height:100%;
}
.item{
	padding-left:20upx;
}
.item.active{
	background:#f5f5f5;
	color:#FD6801 !important;
}
</style>
